#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: app-configuracao
#data:
#  APP_NAME: "Minha App Kubernetes ConfigMap"
#  APP_VERSION: "1.0.1"
#  APP_AUTHOR: "Aslap"

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configuracao
data:
  APP_NAME_CONFIG: "Minha App Kubernetes ConfigMap"
  APP_VERSION_CONFIG: "1.0.1"
  APP_AUTHOR_CONFIG: "Aslap"